language: ruby
rvm:
- 2.4.1
dist: trusty
bundler_args: "--deployment"
sudo: false
cache:
  bundler: true
  directories:
  - node_modules
  yarn: true
node_js:
- '7'
env: TZ=Europe/London
install:
- nvm install node
- node -v
- npm i -g yarn
- yarn
- bundle install
before_script:
- bundle exec rails webpacker:verify_install
before_deploy: "./compile-build"
deploy:
  provider: releases
  api_key:
    secure: M1yP0tQ18WvyO5KriJV1HOKXJCCS9B90a+ocXmMhqFK/rZRTT2HhxD75bYX3BcLPy3gqq1LSRyq0yi0NbkphbRDGI+Goab6xp0Ou2Ilf+DoK9MY5NG1cxECnfr+blrqzv60r8BtXxYBfExhLcqRqie08BSEmA1bn21aNOIstjNwlqZQDaIZlhiccPXKl6hqwuYlggSPMyUXcrvcPi6xxEv1tfuZ73PBIHWWS1TwUW860oLhiQGh9YWkNry+PaHmJsuUY8PeTFsneeF+LoPKjIdStHjL+UUNMrckDHxqfPtkpVy0N8BpUP+gtR10eGGB9fgGLhxAHdEi16lcLe5NDVdl5nV8xwfBZn7fhvcYkirTwJHulaSLjoHdBXhbP+9535UYRvtQVq/PsHeO1Msi7x6YmfG1Rd/JtU+S5Yu6VEvowEM5KC5xjOtIv/04LiSZHIC+eYIsJTc+Wc2upbRgxn/KF5fL/KsA46208jlKPEWu4jX+CSNg53ypzrbw7np0AlN9M5G1mKYADMq8gwrGr4l3cGTC3viyvp0XsB9j5SoEvKl08/dDsTf7tO9EZ6qiKGVloD3FYSTughBEwmy+Ju7PEV+Nk4Tq0EiV35BRJBB7eVfIg2NF+VEZMz6wRaySxS0nKw98vpYyGSncIo1D5ihD6Qz2vpT9m/pVdMMR3L70=
  file: release.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
